### ISSUE TITLE
URL updates even when router is stopped. 

### ISSUE THREAD

**Issue by benjamingeorge** [bytecipher/grapnel#50]
when stopping or canceling a route handler, the URL should not update.  
```
  router.on('match', function(event){
      if(event.route === '/about'){        
          event.preventDefault();
          event.stopPropagation();
      }
  });
```

this cancels properly but the url still updates to http://example.com/about

**Comment by bytecipher** [comment]
@benjamingeorge The match event is called *after* the url is changed. When preventing propagation of that event, you're preventing any subsequent handlers referencing that event.
