### ISSUE TITLE
stop propagation works only if there is no middleware

### ISSUE THREAD

**Issue by arisAlexis** [bytecipher/grapnel#51]
this._router.add('posts/add',this._auth,(req,event)=> {
    event.stopPropagation();
        new PostNewView();
      });
    this._router.add('posts/:postId',(req)=>new SinglePostView({postId:req.params.postId}));

this works as expected only if this._auth is removed

**Comment by bytecipher** [comment]
@arisAlexis `this._auth` is already ran before the middleware that you're defining (the one with the `stopPropagation()` call) has already happened.
